import type { NextPage } from "next"
import Head from "next/head"
import styled from "styled-components"

const Container = styled.div`
  width: 100vw;
  height: 100vh;
`

const ContentContainer = styled.div`
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
`

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <ContentContainer>
          <h1>Miti</h1>
          <div>
            <input type="text" />
            <button type="submit">Submit</button>
          </div>
        </ContentContainer>
      </Container>
    </>
  )
}

export default Home
